"""Build bundled pronunciation clips. Requires piper-tts and imageio-ffmpeg.
Usage: python scripts/generate-audio.py /path/to/en_US-ljspeech-medium.onnx
The synthesis runtime/model are build tools, not app dependencies.
"""
import json, sys, wave, subprocess, tempfile
from pathlib import Path
from piper import PiperVoice, SynthesisConfig
import imageio_ffmpeg
import onnxruntime
root = Path(__file__).resolve().parent.parent
words = json.loads((root/'src/data/words.json').read_text())
voice = PiperVoice.load(sys.argv[1])
# Limit inference parallelism: tiny clips are faster with a small thread pool.
options=onnxruntime.SessionOptions();options.intra_op_num_threads=2
voice.session=onnxruntime.InferenceSession(sys.argv[1],sess_options=options,providers=['CPUExecutionProvider'])
output = root/'assets/audio'; output.mkdir(exist_ok=True)
for i,word in enumerate(words):
 for mode,length in [('normal',1.0),('slow',1.4)]:
  target=output/f'{word["id"]}-{mode}.mp3'
  if target.exists():continue
  with tempfile.NamedTemporaryFile(suffix='.wav') as tmp:
   with wave.open(tmp.name,'wb') as wav:
    voice.synthesize_wav(word['english']+'.',wav,SynthesisConfig(length_scale=length))
   subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(),'-loglevel','error','-y','-i',tmp.name,'-codec:a','libmp3lame','-b:a','64k',str(target)],check=True)
 if (i+1)%50==0:print(f'Generated {i+1}/{len(words)} words',flush=True)
(root/'src/data/audio.ts').write_text('// Generated by scripts/generate-audio.py. Bundled; no runtime network dependency.\nexport const audio: Record<string, {normal:number;slow:number}> = {\n'+''.join(f'  "{w["id"]}": {{normal: require("../../assets/audio/{w["id"]}-normal.mp3"), slow: require("../../assets/audio/{w["id"]}-slow.mp3")}},\n' for w in words)+'};\n')
