// Generated by scripts/generate-audio.py. Bundled; no runtime network dependency.
export const audio: Record<string, { normal: number; slow: number }> = {
  "w-000001": {
    normal: require("../../assets/audio/w-000001-normal.mp3"),
    slow: require("../../assets/audio/w-000001-slow.mp3"),
  },
  "w-000002": {
    normal: require("../../assets/audio/w-000002-normal.mp3"),
    slow: require("../../assets/audio/w-000002-slow.mp3"),
  },
  "w-000003": {
    normal: require("../../assets/audio/w-000003-normal.mp3"),
    slow: require("../../assets/audio/w-000003-slow.mp3"),
  },
  "w-000004": {
    normal: require("../../assets/audio/w-000004-normal.mp3"),
    slow: require("../../assets/audio/w-000004-slow.mp3"),
  },
  "w-000005": {
    normal: require("../../assets/audio/w-000005-normal.mp3"),
    slow: require("../../assets/audio/w-000005-slow.mp3"),
  },
  "w-000006": {
    normal: require("../../assets/audio/w-000006-normal.mp3"),
    slow: require("../../assets/audio/w-000006-slow.mp3"),
  },
  "w-000007": {
    normal: require("../../assets/audio/w-000007-normal.mp3"),
    slow: require("../../assets/audio/w-000007-slow.mp3"),
  },
  "w-000008": {
    normal: require("../../assets/audio/w-000008-normal.mp3"),
    slow: require("../../assets/audio/w-000008-slow.mp3"),
  },
  "w-000009": {
    normal: require("../../assets/audio/w-000009-normal.mp3"),
    slow: require("../../assets/audio/w-000009-slow.mp3"),
  },
  "w-000010": {
    normal: require("../../assets/audio/w-000010-normal.mp3"),
    slow: require("../../assets/audio/w-000010-slow.mp3"),
  },
  "w-000011": {
    normal: require("../../assets/audio/w-000011-normal.mp3"),
    slow: require("../../assets/audio/w-000011-slow.mp3"),
  },
  "w-000012": {
    normal: require("../../assets/audio/w-000012-normal.mp3"),
    slow: require("../../assets/audio/w-000012-slow.mp3"),
  },
  "w-000013": {
    normal: require("../../assets/audio/w-000013-normal.mp3"),
    slow: require("../../assets/audio/w-000013-slow.mp3"),
  },
  "w-000014": {
    normal: require("../../assets/audio/w-000014-normal.mp3"),
    slow: require("../../assets/audio/w-000014-slow.mp3"),
  },
  "w-000015": {
    normal: require("../../assets/audio/w-000015-normal.mp3"),
    slow: require("../../assets/audio/w-000015-slow.mp3"),
  },
  "w-000016": {
    normal: require("../../assets/audio/w-000016-normal.mp3"),
    slow: require("../../assets/audio/w-000016-slow.mp3"),
  },
  "w-000017": {
    normal: require("../../assets/audio/w-000017-normal.mp3"),
    slow: require("../../assets/audio/w-000017-slow.mp3"),
  },
  "w-000018": {
    normal: require("../../assets/audio/w-000018-normal.mp3"),
    slow: require("../../assets/audio/w-000018-slow.mp3"),
  },
  "w-000019": {
    normal: require("../../assets/audio/w-000019-normal.mp3"),
    slow: require("../../assets/audio/w-000019-slow.mp3"),
  },
  "w-000020": {
    normal: require("../../assets/audio/w-000020-normal.mp3"),
    slow: require("../../assets/audio/w-000020-slow.mp3"),
  },
  "w-000021": {
    normal: require("../../assets/audio/w-000021-normal.mp3"),
    slow: require("../../assets/audio/w-000021-slow.mp3"),
  },
  "w-000022": {
    normal: require("../../assets/audio/w-000022-normal.mp3"),
    slow: require("../../assets/audio/w-000022-slow.mp3"),
  },
  "w-000023": {
    normal: require("../../assets/audio/w-000023-normal.mp3"),
    slow: require("../../assets/audio/w-000023-slow.mp3"),
  },
  "w-000024": {
    normal: require("../../assets/audio/w-000024-normal.mp3"),
    slow: require("../../assets/audio/w-000024-slow.mp3"),
  },
  "w-000025": {
    normal: require("../../assets/audio/w-000025-normal.mp3"),
    slow: require("../../assets/audio/w-000025-slow.mp3"),
  },
  "w-000026": {
    normal: require("../../assets/audio/w-000026-normal.mp3"),
    slow: require("../../assets/audio/w-000026-slow.mp3"),
  },
  "w-000027": {
    normal: require("../../assets/audio/w-000027-normal.mp3"),
    slow: require("../../assets/audio/w-000027-slow.mp3"),
  },
  "w-000028": {
    normal: require("../../assets/audio/w-000028-normal.mp3"),
    slow: require("../../assets/audio/w-000028-slow.mp3"),
  },
  "w-000029": {
    normal: require("../../assets/audio/w-000029-normal.mp3"),
    slow: require("../../assets/audio/w-000029-slow.mp3"),
  },
  "w-000030": {
    normal: require("../../assets/audio/w-000030-normal.mp3"),
    slow: require("../../assets/audio/w-000030-slow.mp3"),
  },
  "w-000031": {
    normal: require("../../assets/audio/w-000031-normal.mp3"),
    slow: require("../../assets/audio/w-000031-slow.mp3"),
  },
  "w-000032": {
    normal: require("../../assets/audio/w-000032-normal.mp3"),
    slow: require("../../assets/audio/w-000032-slow.mp3"),
  },
  "w-000033": {
    normal: require("../../assets/audio/w-000033-normal.mp3"),
    slow: require("../../assets/audio/w-000033-slow.mp3"),
  },
  "w-000034": {
    normal: require("../../assets/audio/w-000034-normal.mp3"),
    slow: require("../../assets/audio/w-000034-slow.mp3"),
  },
  "w-000035": {
    normal: require("../../assets/audio/w-000035-normal.mp3"),
    slow: require("../../assets/audio/w-000035-slow.mp3"),
  },
  "w-000036": {
    normal: require("../../assets/audio/w-000036-normal.mp3"),
    slow: require("../../assets/audio/w-000036-slow.mp3"),
  },
  "w-000037": {
    normal: require("../../assets/audio/w-000037-normal.mp3"),
    slow: require("../../assets/audio/w-000037-slow.mp3"),
  },
  "w-000038": {
    normal: require("../../assets/audio/w-000038-normal.mp3"),
    slow: require("../../assets/audio/w-000038-slow.mp3"),
  },
  "w-000039": {
    normal: require("../../assets/audio/w-000039-normal.mp3"),
    slow: require("../../assets/audio/w-000039-slow.mp3"),
  },
  "w-000040": {
    normal: require("../../assets/audio/w-000040-normal.mp3"),
    slow: require("../../assets/audio/w-000040-slow.mp3"),
  },
  "w-000041": {
    normal: require("../../assets/audio/w-000041-normal.mp3"),
    slow: require("../../assets/audio/w-000041-slow.mp3"),
  },
  "w-000042": {
    normal: require("../../assets/audio/w-000042-normal.mp3"),
    slow: require("../../assets/audio/w-000042-slow.mp3"),
  },
  "w-000043": {
    normal: require("../../assets/audio/w-000043-normal.mp3"),
    slow: require("../../assets/audio/w-000043-slow.mp3"),
  },
  "w-000044": {
    normal: require("../../assets/audio/w-000044-normal.mp3"),
    slow: require("../../assets/audio/w-000044-slow.mp3"),
  },
  "w-000045": {
    normal: require("../../assets/audio/w-000045-normal.mp3"),
    slow: require("../../assets/audio/w-000045-slow.mp3"),
  },
  "w-000046": {
    normal: require("../../assets/audio/w-000046-normal.mp3"),
    slow: require("../../assets/audio/w-000046-slow.mp3"),
  },
  "w-000047": {
    normal: require("../../assets/audio/w-000047-normal.mp3"),
    slow: require("../../assets/audio/w-000047-slow.mp3"),
  },
  "w-000048": {
    normal: require("../../assets/audio/w-000048-normal.mp3"),
    slow: require("../../assets/audio/w-000048-slow.mp3"),
  },
  "w-000049": {
    normal: require("../../assets/audio/w-000049-normal.mp3"),
    slow: require("../../assets/audio/w-000049-slow.mp3"),
  },
  "w-000050": {
    normal: require("../../assets/audio/w-000050-normal.mp3"),
    slow: require("../../assets/audio/w-000050-slow.mp3"),
  },
  "w-000051": {
    normal: require("../../assets/audio/w-000051-normal.mp3"),
    slow: require("../../assets/audio/w-000051-slow.mp3"),
  },
  "w-000052": {
    normal: require("../../assets/audio/w-000052-normal.mp3"),
    slow: require("../../assets/audio/w-000052-slow.mp3"),
  },
  "w-000053": {
    normal: require("../../assets/audio/w-000053-normal.mp3"),
    slow: require("../../assets/audio/w-000053-slow.mp3"),
  },
  "w-000054": {
    normal: require("../../assets/audio/w-000054-normal.mp3"),
    slow: require("../../assets/audio/w-000054-slow.mp3"),
  },
  "w-000055": {
    normal: require("../../assets/audio/w-000055-normal.mp3"),
    slow: require("../../assets/audio/w-000055-slow.mp3"),
  },
  "w-000056": {
    normal: require("../../assets/audio/w-000056-normal.mp3"),
    slow: require("../../assets/audio/w-000056-slow.mp3"),
  },
  "w-000057": {
    normal: require("../../assets/audio/w-000057-normal.mp3"),
    slow: require("../../assets/audio/w-000057-slow.mp3"),
  },
  "w-000058": {
    normal: require("../../assets/audio/w-000058-normal.mp3"),
    slow: require("../../assets/audio/w-000058-slow.mp3"),
  },
  "w-000059": {
    normal: require("../../assets/audio/w-000059-normal.mp3"),
    slow: require("../../assets/audio/w-000059-slow.mp3"),
  },
  "w-000060": {
    normal: require("../../assets/audio/w-000060-normal.mp3"),
    slow: require("../../assets/audio/w-000060-slow.mp3"),
  },
  "w-000061": {
    normal: require("../../assets/audio/w-000061-normal.mp3"),
    slow: require("../../assets/audio/w-000061-slow.mp3"),
  },
  "w-000062": {
    normal: require("../../assets/audio/w-000062-normal.mp3"),
    slow: require("../../assets/audio/w-000062-slow.mp3"),
  },
  "w-000063": {
    normal: require("../../assets/audio/w-000063-normal.mp3"),
    slow: require("../../assets/audio/w-000063-slow.mp3"),
  },
  "w-000064": {
    normal: require("../../assets/audio/w-000064-normal.mp3"),
    slow: require("../../assets/audio/w-000064-slow.mp3"),
  },
  "w-000065": {
    normal: require("../../assets/audio/w-000065-normal.mp3"),
    slow: require("../../assets/audio/w-000065-slow.mp3"),
  },
  "w-000066": {
    normal: require("../../assets/audio/w-000066-normal.mp3"),
    slow: require("../../assets/audio/w-000066-slow.mp3"),
  },
  "w-000067": {
    normal: require("../../assets/audio/w-000067-normal.mp3"),
    slow: require("../../assets/audio/w-000067-slow.mp3"),
  },
  "w-000068": {
    normal: require("../../assets/audio/w-000068-normal.mp3"),
    slow: require("../../assets/audio/w-000068-slow.mp3"),
  },
  "w-000069": {
    normal: require("../../assets/audio/w-000069-normal.mp3"),
    slow: require("../../assets/audio/w-000069-slow.mp3"),
  },
  "w-000070": {
    normal: require("../../assets/audio/w-000070-normal.mp3"),
    slow: require("../../assets/audio/w-000070-slow.mp3"),
  },
  "w-000071": {
    normal: require("../../assets/audio/w-000071-normal.mp3"),
    slow: require("../../assets/audio/w-000071-slow.mp3"),
  },
  "w-000072": {
    normal: require("../../assets/audio/w-000072-normal.mp3"),
    slow: require("../../assets/audio/w-000072-slow.mp3"),
  },
  "w-000073": {
    normal: require("../../assets/audio/w-000073-normal.mp3"),
    slow: require("../../assets/audio/w-000073-slow.mp3"),
  },
  "w-000074": {
    normal: require("../../assets/audio/w-000074-normal.mp3"),
    slow: require("../../assets/audio/w-000074-slow.mp3"),
  },
  "w-000075": {
    normal: require("../../assets/audio/w-000075-normal.mp3"),
    slow: require("../../assets/audio/w-000075-slow.mp3"),
  },
  "w-000076": {
    normal: require("../../assets/audio/w-000076-normal.mp3"),
    slow: require("../../assets/audio/w-000076-slow.mp3"),
  },
  "w-000077": {
    normal: require("../../assets/audio/w-000077-normal.mp3"),
    slow: require("../../assets/audio/w-000077-slow.mp3"),
  },
  "w-000078": {
    normal: require("../../assets/audio/w-000078-normal.mp3"),
    slow: require("../../assets/audio/w-000078-slow.mp3"),
  },
  "w-000079": {
    normal: require("../../assets/audio/w-000079-normal.mp3"),
    slow: require("../../assets/audio/w-000079-slow.mp3"),
  },
  "w-000080": {
    normal: require("../../assets/audio/w-000080-normal.mp3"),
    slow: require("../../assets/audio/w-000080-slow.mp3"),
  },
  "w-000081": {
    normal: require("../../assets/audio/w-000081-normal.mp3"),
    slow: require("../../assets/audio/w-000081-slow.mp3"),
  },
  "w-000082": {
    normal: require("../../assets/audio/w-000082-normal.mp3"),
    slow: require("../../assets/audio/w-000082-slow.mp3"),
  },
  "w-000083": {
    normal: require("../../assets/audio/w-000083-normal.mp3"),
    slow: require("../../assets/audio/w-000083-slow.mp3"),
  },
  "w-000084": {
    normal: require("../../assets/audio/w-000084-normal.mp3"),
    slow: require("../../assets/audio/w-000084-slow.mp3"),
  },
  "w-000085": {
    normal: require("../../assets/audio/w-000085-normal.mp3"),
    slow: require("../../assets/audio/w-000085-slow.mp3"),
  },
  "w-000086": {
    normal: require("../../assets/audio/w-000086-normal.mp3"),
    slow: require("../../assets/audio/w-000086-slow.mp3"),
  },
  "w-000087": {
    normal: require("../../assets/audio/w-000087-normal.mp3"),
    slow: require("../../assets/audio/w-000087-slow.mp3"),
  },
  "w-000088": {
    normal: require("../../assets/audio/w-000088-normal.mp3"),
    slow: require("../../assets/audio/w-000088-slow.mp3"),
  },
  "w-000089": {
    normal: require("../../assets/audio/w-000089-normal.mp3"),
    slow: require("../../assets/audio/w-000089-slow.mp3"),
  },
  "w-000090": {
    normal: require("../../assets/audio/w-000090-normal.mp3"),
    slow: require("../../assets/audio/w-000090-slow.mp3"),
  },
  "w-000091": {
    normal: require("../../assets/audio/w-000091-normal.mp3"),
    slow: require("../../assets/audio/w-000091-slow.mp3"),
  },
  "w-000092": {
    normal: require("../../assets/audio/w-000092-normal.mp3"),
    slow: require("../../assets/audio/w-000092-slow.mp3"),
  },
  "w-000093": {
    normal: require("../../assets/audio/w-000093-normal.mp3"),
    slow: require("../../assets/audio/w-000093-slow.mp3"),
  },
  "w-000094": {
    normal: require("../../assets/audio/w-000094-normal.mp3"),
    slow: require("../../assets/audio/w-000094-slow.mp3"),
  },
  "w-000095": {
    normal: require("../../assets/audio/w-000095-normal.mp3"),
    slow: require("../../assets/audio/w-000095-slow.mp3"),
  },
  "w-000096": {
    normal: require("../../assets/audio/w-000096-normal.mp3"),
    slow: require("../../assets/audio/w-000096-slow.mp3"),
  },
  "w-000097": {
    normal: require("../../assets/audio/w-000097-normal.mp3"),
    slow: require("../../assets/audio/w-000097-slow.mp3"),
  },
  "w-000098": {
    normal: require("../../assets/audio/w-000098-normal.mp3"),
    slow: require("../../assets/audio/w-000098-slow.mp3"),
  },
  "w-000099": {
    normal: require("../../assets/audio/w-000099-normal.mp3"),
    slow: require("../../assets/audio/w-000099-slow.mp3"),
  },
  "w-000100": {
    normal: require("../../assets/audio/w-000100-normal.mp3"),
    slow: require("../../assets/audio/w-000100-slow.mp3"),
  },
  "w-000101": {
    normal: require("../../assets/audio/w-000101-normal.mp3"),
    slow: require("../../assets/audio/w-000101-slow.mp3"),
  },
  "w-000102": {
    normal: require("../../assets/audio/w-000102-normal.mp3"),
    slow: require("../../assets/audio/w-000102-slow.mp3"),
  },
  "w-000103": {
    normal: require("../../assets/audio/w-000103-normal.mp3"),
    slow: require("../../assets/audio/w-000103-slow.mp3"),
  },
  "w-000104": {
    normal: require("../../assets/audio/w-000104-normal.mp3"),
    slow: require("../../assets/audio/w-000104-slow.mp3"),
  },
  "w-000105": {
    normal: require("../../assets/audio/w-000105-normal.mp3"),
    slow: require("../../assets/audio/w-000105-slow.mp3"),
  },
  "w-000106": {
    normal: require("../../assets/audio/w-000106-normal.mp3"),
    slow: require("../../assets/audio/w-000106-slow.mp3"),
  },
  "w-000107": {
    normal: require("../../assets/audio/w-000107-normal.mp3"),
    slow: require("../../assets/audio/w-000107-slow.mp3"),
  },
  "w-000108": {
    normal: require("../../assets/audio/w-000108-normal.mp3"),
    slow: require("../../assets/audio/w-000108-slow.mp3"),
  },
  "w-000109": {
    normal: require("../../assets/audio/w-000109-normal.mp3"),
    slow: require("../../assets/audio/w-000109-slow.mp3"),
  },
  "w-000110": {
    normal: require("../../assets/audio/w-000110-normal.mp3"),
    slow: require("../../assets/audio/w-000110-slow.mp3"),
  },
  "w-000111": {
    normal: require("../../assets/audio/w-000111-normal.mp3"),
    slow: require("../../assets/audio/w-000111-slow.mp3"),
  },
  "w-000112": {
    normal: require("../../assets/audio/w-000112-normal.mp3"),
    slow: require("../../assets/audio/w-000112-slow.mp3"),
  },
  "w-000113": {
    normal: require("../../assets/audio/w-000113-normal.mp3"),
    slow: require("../../assets/audio/w-000113-slow.mp3"),
  },
  "w-000114": {
    normal: require("../../assets/audio/w-000114-normal.mp3"),
    slow: require("../../assets/audio/w-000114-slow.mp3"),
  },
  "w-000115": {
    normal: require("../../assets/audio/w-000115-normal.mp3"),
    slow: require("../../assets/audio/w-000115-slow.mp3"),
  },
  "w-000116": {
    normal: require("../../assets/audio/w-000116-normal.mp3"),
    slow: require("../../assets/audio/w-000116-slow.mp3"),
  },
  "w-000117": {
    normal: require("../../assets/audio/w-000117-normal.mp3"),
    slow: require("../../assets/audio/w-000117-slow.mp3"),
  },
  "w-000118": {
    normal: require("../../assets/audio/w-000118-normal.mp3"),
    slow: require("../../assets/audio/w-000118-slow.mp3"),
  },
  "w-000119": {
    normal: require("../../assets/audio/w-000119-normal.mp3"),
    slow: require("../../assets/audio/w-000119-slow.mp3"),
  },
  "w-000120": {
    normal: require("../../assets/audio/w-000120-normal.mp3"),
    slow: require("../../assets/audio/w-000120-slow.mp3"),
  },
  "w-000121": {
    normal: require("../../assets/audio/w-000121-normal.mp3"),
    slow: require("../../assets/audio/w-000121-slow.mp3"),
  },
  "w-000122": {
    normal: require("../../assets/audio/w-000122-normal.mp3"),
    slow: require("../../assets/audio/w-000122-slow.mp3"),
  },
  "w-000123": {
    normal: require("../../assets/audio/w-000123-normal.mp3"),
    slow: require("../../assets/audio/w-000123-slow.mp3"),
  },
  "w-000124": {
    normal: require("../../assets/audio/w-000124-normal.mp3"),
    slow: require("../../assets/audio/w-000124-slow.mp3"),
  },
  "w-000125": {
    normal: require("../../assets/audio/w-000125-normal.mp3"),
    slow: require("../../assets/audio/w-000125-slow.mp3"),
  },
  "w-000126": {
    normal: require("../../assets/audio/w-000126-normal.mp3"),
    slow: require("../../assets/audio/w-000126-slow.mp3"),
  },
  "w-000127": {
    normal: require("../../assets/audio/w-000127-normal.mp3"),
    slow: require("../../assets/audio/w-000127-slow.mp3"),
  },
  "w-000128": {
    normal: require("../../assets/audio/w-000128-normal.mp3"),
    slow: require("../../assets/audio/w-000128-slow.mp3"),
  },
  "w-000129": {
    normal: require("../../assets/audio/w-000129-normal.mp3"),
    slow: require("../../assets/audio/w-000129-slow.mp3"),
  },
  "w-000130": {
    normal: require("../../assets/audio/w-000130-normal.mp3"),
    slow: require("../../assets/audio/w-000130-slow.mp3"),
  },
  "w-000131": {
    normal: require("../../assets/audio/w-000131-normal.mp3"),
    slow: require("../../assets/audio/w-000131-slow.mp3"),
  },
  "w-000132": {
    normal: require("../../assets/audio/w-000132-normal.mp3"),
    slow: require("../../assets/audio/w-000132-slow.mp3"),
  },
  "w-000133": {
    normal: require("../../assets/audio/w-000133-normal.mp3"),
    slow: require("../../assets/audio/w-000133-slow.mp3"),
  },
  "w-000134": {
    normal: require("../../assets/audio/w-000134-normal.mp3"),
    slow: require("../../assets/audio/w-000134-slow.mp3"),
  },
  "w-000135": {
    normal: require("../../assets/audio/w-000135-normal.mp3"),
    slow: require("../../assets/audio/w-000135-slow.mp3"),
  },
  "w-000136": {
    normal: require("../../assets/audio/w-000136-normal.mp3"),
    slow: require("../../assets/audio/w-000136-slow.mp3"),
  },
  "w-000137": {
    normal: require("../../assets/audio/w-000137-normal.mp3"),
    slow: require("../../assets/audio/w-000137-slow.mp3"),
  },
  "w-000138": {
    normal: require("../../assets/audio/w-000138-normal.mp3"),
    slow: require("../../assets/audio/w-000138-slow.mp3"),
  },
  "w-000139": {
    normal: require("../../assets/audio/w-000139-normal.mp3"),
    slow: require("../../assets/audio/w-000139-slow.mp3"),
  },
  "w-000140": {
    normal: require("../../assets/audio/w-000140-normal.mp3"),
    slow: require("../../assets/audio/w-000140-slow.mp3"),
  },
  "w-000141": {
    normal: require("../../assets/audio/w-000141-normal.mp3"),
    slow: require("../../assets/audio/w-000141-slow.mp3"),
  },
  "w-000142": {
    normal: require("../../assets/audio/w-000142-normal.mp3"),
    slow: require("../../assets/audio/w-000142-slow.mp3"),
  },
  "w-000143": {
    normal: require("../../assets/audio/w-000143-normal.mp3"),
    slow: require("../../assets/audio/w-000143-slow.mp3"),
  },
  "w-000144": {
    normal: require("../../assets/audio/w-000144-normal.mp3"),
    slow: require("../../assets/audio/w-000144-slow.mp3"),
  },
  "w-000145": {
    normal: require("../../assets/audio/w-000145-normal.mp3"),
    slow: require("../../assets/audio/w-000145-slow.mp3"),
  },
  "w-000146": {
    normal: require("../../assets/audio/w-000146-normal.mp3"),
    slow: require("../../assets/audio/w-000146-slow.mp3"),
  },
  "w-000147": {
    normal: require("../../assets/audio/w-000147-normal.mp3"),
    slow: require("../../assets/audio/w-000147-slow.mp3"),
  },
  "w-000148": {
    normal: require("../../assets/audio/w-000148-normal.mp3"),
    slow: require("../../assets/audio/w-000148-slow.mp3"),
  },
  "w-000149": {
    normal: require("../../assets/audio/w-000149-normal.mp3"),
    slow: require("../../assets/audio/w-000149-slow.mp3"),
  },
  "w-000150": {
    normal: require("../../assets/audio/w-000150-normal.mp3"),
    slow: require("../../assets/audio/w-000150-slow.mp3"),
  },
  "w-000151": {
    normal: require("../../assets/audio/w-000151-normal.mp3"),
    slow: require("../../assets/audio/w-000151-slow.mp3"),
  },
  "w-000152": {
    normal: require("../../assets/audio/w-000152-normal.mp3"),
    slow: require("../../assets/audio/w-000152-slow.mp3"),
  },
  "w-000153": {
    normal: require("../../assets/audio/w-000153-normal.mp3"),
    slow: require("../../assets/audio/w-000153-slow.mp3"),
  },
  "w-000154": {
    normal: require("../../assets/audio/w-000154-normal.mp3"),
    slow: require("../../assets/audio/w-000154-slow.mp3"),
  },
  "w-000155": {
    normal: require("../../assets/audio/w-000155-normal.mp3"),
    slow: require("../../assets/audio/w-000155-slow.mp3"),
  },
  "w-000156": {
    normal: require("../../assets/audio/w-000156-normal.mp3"),
    slow: require("../../assets/audio/w-000156-slow.mp3"),
  },
  "w-000157": {
    normal: require("../../assets/audio/w-000157-normal.mp3"),
    slow: require("../../assets/audio/w-000157-slow.mp3"),
  },
  "w-000158": {
    normal: require("../../assets/audio/w-000158-normal.mp3"),
    slow: require("../../assets/audio/w-000158-slow.mp3"),
  },
  "w-000159": {
    normal: require("../../assets/audio/w-000159-normal.mp3"),
    slow: require("../../assets/audio/w-000159-slow.mp3"),
  },
  "w-000160": {
    normal: require("../../assets/audio/w-000160-normal.mp3"),
    slow: require("../../assets/audio/w-000160-slow.mp3"),
  },
  "w-000161": {
    normal: require("../../assets/audio/w-000161-normal.mp3"),
    slow: require("../../assets/audio/w-000161-slow.mp3"),
  },
  "w-000162": {
    normal: require("../../assets/audio/w-000162-normal.mp3"),
    slow: require("../../assets/audio/w-000162-slow.mp3"),
  },
  "w-000163": {
    normal: require("../../assets/audio/w-000163-normal.mp3"),
    slow: require("../../assets/audio/w-000163-slow.mp3"),
  },
  "w-000164": {
    normal: require("../../assets/audio/w-000164-normal.mp3"),
    slow: require("../../assets/audio/w-000164-slow.mp3"),
  },
  "w-000165": {
    normal: require("../../assets/audio/w-000165-normal.mp3"),
    slow: require("../../assets/audio/w-000165-slow.mp3"),
  },
  "w-000166": {
    normal: require("../../assets/audio/w-000166-normal.mp3"),
    slow: require("../../assets/audio/w-000166-slow.mp3"),
  },
  "w-000167": {
    normal: require("../../assets/audio/w-000167-normal.mp3"),
    slow: require("../../assets/audio/w-000167-slow.mp3"),
  },
  "w-000168": {
    normal: require("../../assets/audio/w-000168-normal.mp3"),
    slow: require("../../assets/audio/w-000168-slow.mp3"),
  },
  "w-000169": {
    normal: require("../../assets/audio/w-000169-normal.mp3"),
    slow: require("../../assets/audio/w-000169-slow.mp3"),
  },
  "w-000170": {
    normal: require("../../assets/audio/w-000170-normal.mp3"),
    slow: require("../../assets/audio/w-000170-slow.mp3"),
  },
  "w-000171": {
    normal: require("../../assets/audio/w-000171-normal.mp3"),
    slow: require("../../assets/audio/w-000171-slow.mp3"),
  },
  "w-000172": {
    normal: require("../../assets/audio/w-000172-normal.mp3"),
    slow: require("../../assets/audio/w-000172-slow.mp3"),
  },
  "w-000173": {
    normal: require("../../assets/audio/w-000173-normal.mp3"),
    slow: require("../../assets/audio/w-000173-slow.mp3"),
  },
  "w-000174": {
    normal: require("../../assets/audio/w-000174-normal.mp3"),
    slow: require("../../assets/audio/w-000174-slow.mp3"),
  },
  "w-000175": {
    normal: require("../../assets/audio/w-000175-normal.mp3"),
    slow: require("../../assets/audio/w-000175-slow.mp3"),
  },
  "w-000176": {
    normal: require("../../assets/audio/w-000176-normal.mp3"),
    slow: require("../../assets/audio/w-000176-slow.mp3"),
  },
  "w-000177": {
    normal: require("../../assets/audio/w-000177-normal.mp3"),
    slow: require("../../assets/audio/w-000177-slow.mp3"),
  },
  "w-000178": {
    normal: require("../../assets/audio/w-000178-normal.mp3"),
    slow: require("../../assets/audio/w-000178-slow.mp3"),
  },
  "w-000179": {
    normal: require("../../assets/audio/w-000179-normal.mp3"),
    slow: require("../../assets/audio/w-000179-slow.mp3"),
  },
  "w-000180": {
    normal: require("../../assets/audio/w-000180-normal.mp3"),
    slow: require("../../assets/audio/w-000180-slow.mp3"),
  },
  "w-000181": {
    normal: require("../../assets/audio/w-000181-normal.mp3"),
    slow: require("../../assets/audio/w-000181-slow.mp3"),
  },
  "w-000182": {
    normal: require("../../assets/audio/w-000182-normal.mp3"),
    slow: require("../../assets/audio/w-000182-slow.mp3"),
  },
  "w-000183": {
    normal: require("../../assets/audio/w-000183-normal.mp3"),
    slow: require("../../assets/audio/w-000183-slow.mp3"),
  },
  "w-000184": {
    normal: require("../../assets/audio/w-000184-normal.mp3"),
    slow: require("../../assets/audio/w-000184-slow.mp3"),
  },
  "w-000185": {
    normal: require("../../assets/audio/w-000185-normal.mp3"),
    slow: require("../../assets/audio/w-000185-slow.mp3"),
  },
  "w-000186": {
    normal: require("../../assets/audio/w-000186-normal.mp3"),
    slow: require("../../assets/audio/w-000186-slow.mp3"),
  },
  "w-000187": {
    normal: require("../../assets/audio/w-000187-normal.mp3"),
    slow: require("../../assets/audio/w-000187-slow.mp3"),
  },
  "w-000188": {
    normal: require("../../assets/audio/w-000188-normal.mp3"),
    slow: require("../../assets/audio/w-000188-slow.mp3"),
  },
  "w-000189": {
    normal: require("../../assets/audio/w-000189-normal.mp3"),
    slow: require("../../assets/audio/w-000189-slow.mp3"),
  },
  "w-000190": {
    normal: require("../../assets/audio/w-000190-normal.mp3"),
    slow: require("../../assets/audio/w-000190-slow.mp3"),
  },
  "w-000191": {
    normal: require("../../assets/audio/w-000191-normal.mp3"),
    slow: require("../../assets/audio/w-000191-slow.mp3"),
  },
  "w-000192": {
    normal: require("../../assets/audio/w-000192-normal.mp3"),
    slow: require("../../assets/audio/w-000192-slow.mp3"),
  },
  "w-000193": {
    normal: require("../../assets/audio/w-000193-normal.mp3"),
    slow: require("../../assets/audio/w-000193-slow.mp3"),
  },
  "w-000194": {
    normal: require("../../assets/audio/w-000194-normal.mp3"),
    slow: require("../../assets/audio/w-000194-slow.mp3"),
  },
  "w-000195": {
    normal: require("../../assets/audio/w-000195-normal.mp3"),
    slow: require("../../assets/audio/w-000195-slow.mp3"),
  },
  "w-000196": {
    normal: require("../../assets/audio/w-000196-normal.mp3"),
    slow: require("../../assets/audio/w-000196-slow.mp3"),
  },
  "w-000197": {
    normal: require("../../assets/audio/w-000197-normal.mp3"),
    slow: require("../../assets/audio/w-000197-slow.mp3"),
  },
  "w-000198": {
    normal: require("../../assets/audio/w-000198-normal.mp3"),
    slow: require("../../assets/audio/w-000198-slow.mp3"),
  },
  "w-000199": {
    normal: require("../../assets/audio/w-000199-normal.mp3"),
    slow: require("../../assets/audio/w-000199-slow.mp3"),
  },
  "w-000200": {
    normal: require("../../assets/audio/w-000200-normal.mp3"),
    slow: require("../../assets/audio/w-000200-slow.mp3"),
  },
  "w-000201": {
    normal: require("../../assets/audio/w-000201-normal.mp3"),
    slow: require("../../assets/audio/w-000201-slow.mp3"),
  },
  "w-000202": {
    normal: require("../../assets/audio/w-000202-normal.mp3"),
    slow: require("../../assets/audio/w-000202-slow.mp3"),
  },
  "w-000203": {
    normal: require("../../assets/audio/w-000203-normal.mp3"),
    slow: require("../../assets/audio/w-000203-slow.mp3"),
  },
  "w-000204": {
    normal: require("../../assets/audio/w-000204-normal.mp3"),
    slow: require("../../assets/audio/w-000204-slow.mp3"),
  },
  "w-000205": {
    normal: require("../../assets/audio/w-000205-normal.mp3"),
    slow: require("../../assets/audio/w-000205-slow.mp3"),
  },
  "w-000206": {
    normal: require("../../assets/audio/w-000206-normal.mp3"),
    slow: require("../../assets/audio/w-000206-slow.mp3"),
  },
  "w-000207": {
    normal: require("../../assets/audio/w-000207-normal.mp3"),
    slow: require("../../assets/audio/w-000207-slow.mp3"),
  },
  "w-000208": {
    normal: require("../../assets/audio/w-000208-normal.mp3"),
    slow: require("../../assets/audio/w-000208-slow.mp3"),
  },
  "w-000209": {
    normal: require("../../assets/audio/w-000209-normal.mp3"),
    slow: require("../../assets/audio/w-000209-slow.mp3"),
  },
  "w-000210": {
    normal: require("../../assets/audio/w-000210-normal.mp3"),
    slow: require("../../assets/audio/w-000210-slow.mp3"),
  },
  "w-000211": {
    normal: require("../../assets/audio/w-000211-normal.mp3"),
    slow: require("../../assets/audio/w-000211-slow.mp3"),
  },
  "w-000212": {
    normal: require("../../assets/audio/w-000212-normal.mp3"),
    slow: require("../../assets/audio/w-000212-slow.mp3"),
  },
  "w-000213": {
    normal: require("../../assets/audio/w-000213-normal.mp3"),
    slow: require("../../assets/audio/w-000213-slow.mp3"),
  },
  "w-000214": {
    normal: require("../../assets/audio/w-000214-normal.mp3"),
    slow: require("../../assets/audio/w-000214-slow.mp3"),
  },
  "w-000215": {
    normal: require("../../assets/audio/w-000215-normal.mp3"),
    slow: require("../../assets/audio/w-000215-slow.mp3"),
  },
  "w-000216": {
    normal: require("../../assets/audio/w-000216-normal.mp3"),
    slow: require("../../assets/audio/w-000216-slow.mp3"),
  },
  "w-000217": {
    normal: require("../../assets/audio/w-000217-normal.mp3"),
    slow: require("../../assets/audio/w-000217-slow.mp3"),
  },
  "w-000218": {
    normal: require("../../assets/audio/w-000218-normal.mp3"),
    slow: require("../../assets/audio/w-000218-slow.mp3"),
  },
  "w-000219": {
    normal: require("../../assets/audio/w-000219-normal.mp3"),
    slow: require("../../assets/audio/w-000219-slow.mp3"),
  },
  "w-000220": {
    normal: require("../../assets/audio/w-000220-normal.mp3"),
    slow: require("../../assets/audio/w-000220-slow.mp3"),
  },
  "w-000221": {
    normal: require("../../assets/audio/w-000221-normal.mp3"),
    slow: require("../../assets/audio/w-000221-slow.mp3"),
  },
  "w-000222": {
    normal: require("../../assets/audio/w-000222-normal.mp3"),
    slow: require("../../assets/audio/w-000222-slow.mp3"),
  },
  "w-000223": {
    normal: require("../../assets/audio/w-000223-normal.mp3"),
    slow: require("../../assets/audio/w-000223-slow.mp3"),
  },
  "w-000224": {
    normal: require("../../assets/audio/w-000224-normal.mp3"),
    slow: require("../../assets/audio/w-000224-slow.mp3"),
  },
  "w-000225": {
    normal: require("../../assets/audio/w-000225-normal.mp3"),
    slow: require("../../assets/audio/w-000225-slow.mp3"),
  },
  "w-000226": {
    normal: require("../../assets/audio/w-000226-normal.mp3"),
    slow: require("../../assets/audio/w-000226-slow.mp3"),
  },
  "w-000227": {
    normal: require("../../assets/audio/w-000227-normal.mp3"),
    slow: require("../../assets/audio/w-000227-slow.mp3"),
  },
  "w-000228": {
    normal: require("../../assets/audio/w-000228-normal.mp3"),
    slow: require("../../assets/audio/w-000228-slow.mp3"),
  },
  "w-000229": {
    normal: require("../../assets/audio/w-000229-normal.mp3"),
    slow: require("../../assets/audio/w-000229-slow.mp3"),
  },
  "w-000230": {
    normal: require("../../assets/audio/w-000230-normal.mp3"),
    slow: require("../../assets/audio/w-000230-slow.mp3"),
  },
  "w-000231": {
    normal: require("../../assets/audio/w-000231-normal.mp3"),
    slow: require("../../assets/audio/w-000231-slow.mp3"),
  },
  "w-000232": {
    normal: require("../../assets/audio/w-000232-normal.mp3"),
    slow: require("../../assets/audio/w-000232-slow.mp3"),
  },
  "w-000233": {
    normal: require("../../assets/audio/w-000233-normal.mp3"),
    slow: require("../../assets/audio/w-000233-slow.mp3"),
  },
  "w-000234": {
    normal: require("../../assets/audio/w-000234-normal.mp3"),
    slow: require("../../assets/audio/w-000234-slow.mp3"),
  },
  "w-000235": {
    normal: require("../../assets/audio/w-000235-normal.mp3"),
    slow: require("../../assets/audio/w-000235-slow.mp3"),
  },
  "w-000236": {
    normal: require("../../assets/audio/w-000236-normal.mp3"),
    slow: require("../../assets/audio/w-000236-slow.mp3"),
  },
  "w-000237": {
    normal: require("../../assets/audio/w-000237-normal.mp3"),
    slow: require("../../assets/audio/w-000237-slow.mp3"),
  },
  "w-000238": {
    normal: require("../../assets/audio/w-000238-normal.mp3"),
    slow: require("../../assets/audio/w-000238-slow.mp3"),
  },
  "w-000239": {
    normal: require("../../assets/audio/w-000239-normal.mp3"),
    slow: require("../../assets/audio/w-000239-slow.mp3"),
  },
  "w-000240": {
    normal: require("../../assets/audio/w-000240-normal.mp3"),
    slow: require("../../assets/audio/w-000240-slow.mp3"),
  },
  "w-000241": {
    normal: require("../../assets/audio/w-000241-normal.mp3"),
    slow: require("../../assets/audio/w-000241-slow.mp3"),
  },
  "w-000242": {
    normal: require("../../assets/audio/w-000242-normal.mp3"),
    slow: require("../../assets/audio/w-000242-slow.mp3"),
  },
  "w-000243": {
    normal: require("../../assets/audio/w-000243-normal.mp3"),
    slow: require("../../assets/audio/w-000243-slow.mp3"),
  },
  "w-000244": {
    normal: require("../../assets/audio/w-000244-normal.mp3"),
    slow: require("../../assets/audio/w-000244-slow.mp3"),
  },
  "w-000245": {
    normal: require("../../assets/audio/w-000245-normal.mp3"),
    slow: require("../../assets/audio/w-000245-slow.mp3"),
  },
  "w-000246": {
    normal: require("../../assets/audio/w-000246-normal.mp3"),
    slow: require("../../assets/audio/w-000246-slow.mp3"),
  },
  "w-000247": {
    normal: require("../../assets/audio/w-000247-normal.mp3"),
    slow: require("../../assets/audio/w-000247-slow.mp3"),
  },
  "w-000248": {
    normal: require("../../assets/audio/w-000248-normal.mp3"),
    slow: require("../../assets/audio/w-000248-slow.mp3"),
  },
  "w-000249": {
    normal: require("../../assets/audio/w-000249-normal.mp3"),
    slow: require("../../assets/audio/w-000249-slow.mp3"),
  },
  "w-000250": {
    normal: require("../../assets/audio/w-000250-normal.mp3"),
    slow: require("../../assets/audio/w-000250-slow.mp3"),
  },
  "w-000251": {
    normal: require("../../assets/audio/w-000251-normal.mp3"),
    slow: require("../../assets/audio/w-000251-slow.mp3"),
  },
  "w-000252": {
    normal: require("../../assets/audio/w-000252-normal.mp3"),
    slow: require("../../assets/audio/w-000252-slow.mp3"),
  },
  "w-000253": {
    normal: require("../../assets/audio/w-000253-normal.mp3"),
    slow: require("../../assets/audio/w-000253-slow.mp3"),
  },
  "w-000254": {
    normal: require("../../assets/audio/w-000254-normal.mp3"),
    slow: require("../../assets/audio/w-000254-slow.mp3"),
  },
  "w-000255": {
    normal: require("../../assets/audio/w-000255-normal.mp3"),
    slow: require("../../assets/audio/w-000255-slow.mp3"),
  },
  "w-000256": {
    normal: require("../../assets/audio/w-000256-normal.mp3"),
    slow: require("../../assets/audio/w-000256-slow.mp3"),
  },
  "w-000257": {
    normal: require("../../assets/audio/w-000257-normal.mp3"),
    slow: require("../../assets/audio/w-000257-slow.mp3"),
  },
  "w-000258": {
    normal: require("../../assets/audio/w-000258-normal.mp3"),
    slow: require("../../assets/audio/w-000258-slow.mp3"),
  },
  "w-000259": {
    normal: require("../../assets/audio/w-000259-normal.mp3"),
    slow: require("../../assets/audio/w-000259-slow.mp3"),
  },
  "w-000260": {
    normal: require("../../assets/audio/w-000260-normal.mp3"),
    slow: require("../../assets/audio/w-000260-slow.mp3"),
  },
  "w-000261": {
    normal: require("../../assets/audio/w-000261-normal.mp3"),
    slow: require("../../assets/audio/w-000261-slow.mp3"),
  },
  "w-000262": {
    normal: require("../../assets/audio/w-000262-normal.mp3"),
    slow: require("../../assets/audio/w-000262-slow.mp3"),
  },
  "w-000263": {
    normal: require("../../assets/audio/w-000263-normal.mp3"),
    slow: require("../../assets/audio/w-000263-slow.mp3"),
  },
  "w-000264": {
    normal: require("../../assets/audio/w-000264-normal.mp3"),
    slow: require("../../assets/audio/w-000264-slow.mp3"),
  },
  "w-000265": {
    normal: require("../../assets/audio/w-000265-normal.mp3"),
    slow: require("../../assets/audio/w-000265-slow.mp3"),
  },
  "w-000266": {
    normal: require("../../assets/audio/w-000266-normal.mp3"),
    slow: require("../../assets/audio/w-000266-slow.mp3"),
  },
  "w-000267": {
    normal: require("../../assets/audio/w-000267-normal.mp3"),
    slow: require("../../assets/audio/w-000267-slow.mp3"),
  },
  "w-000268": {
    normal: require("../../assets/audio/w-000268-normal.mp3"),
    slow: require("../../assets/audio/w-000268-slow.mp3"),
  },
  "w-000269": {
    normal: require("../../assets/audio/w-000269-normal.mp3"),
    slow: require("../../assets/audio/w-000269-slow.mp3"),
  },
  "w-000270": {
    normal: require("../../assets/audio/w-000270-normal.mp3"),
    slow: require("../../assets/audio/w-000270-slow.mp3"),
  },
  "w-000271": {
    normal: require("../../assets/audio/w-000271-normal.mp3"),
    slow: require("../../assets/audio/w-000271-slow.mp3"),
  },
  "w-000272": {
    normal: require("../../assets/audio/w-000272-normal.mp3"),
    slow: require("../../assets/audio/w-000272-slow.mp3"),
  },
  "w-000273": {
    normal: require("../../assets/audio/w-000273-normal.mp3"),
    slow: require("../../assets/audio/w-000273-slow.mp3"),
  },
  "w-000274": {
    normal: require("../../assets/audio/w-000274-normal.mp3"),
    slow: require("../../assets/audio/w-000274-slow.mp3"),
  },
  "w-000275": {
    normal: require("../../assets/audio/w-000275-normal.mp3"),
    slow: require("../../assets/audio/w-000275-slow.mp3"),
  },
  "w-000276": {
    normal: require("../../assets/audio/w-000276-normal.mp3"),
    slow: require("../../assets/audio/w-000276-slow.mp3"),
  },
  "w-000277": {
    normal: require("../../assets/audio/w-000277-normal.mp3"),
    slow: require("../../assets/audio/w-000277-slow.mp3"),
  },
  "w-000278": {
    normal: require("../../assets/audio/w-000278-normal.mp3"),
    slow: require("../../assets/audio/w-000278-slow.mp3"),
  },
  "w-000279": {
    normal: require("../../assets/audio/w-000279-normal.mp3"),
    slow: require("../../assets/audio/w-000279-slow.mp3"),
  },
  "w-000280": {
    normal: require("../../assets/audio/w-000280-normal.mp3"),
    slow: require("../../assets/audio/w-000280-slow.mp3"),
  },
  "w-000281": {
    normal: require("../../assets/audio/w-000281-normal.mp3"),
    slow: require("../../assets/audio/w-000281-slow.mp3"),
  },
  "w-000282": {
    normal: require("../../assets/audio/w-000282-normal.mp3"),
    slow: require("../../assets/audio/w-000282-slow.mp3"),
  },
  "w-000283": {
    normal: require("../../assets/audio/w-000283-normal.mp3"),
    slow: require("../../assets/audio/w-000283-slow.mp3"),
  },
  "w-000284": {
    normal: require("../../assets/audio/w-000284-normal.mp3"),
    slow: require("../../assets/audio/w-000284-slow.mp3"),
  },
  "w-000285": {
    normal: require("../../assets/audio/w-000285-normal.mp3"),
    slow: require("../../assets/audio/w-000285-slow.mp3"),
  },
  "w-000286": {
    normal: require("../../assets/audio/w-000286-normal.mp3"),
    slow: require("../../assets/audio/w-000286-slow.mp3"),
  },
  "w-000287": {
    normal: require("../../assets/audio/w-000287-normal.mp3"),
    slow: require("../../assets/audio/w-000287-slow.mp3"),
  },
  "w-000288": {
    normal: require("../../assets/audio/w-000288-normal.mp3"),
    slow: require("../../assets/audio/w-000288-slow.mp3"),
  },
  "w-000289": {
    normal: require("../../assets/audio/w-000289-normal.mp3"),
    slow: require("../../assets/audio/w-000289-slow.mp3"),
  },
  "w-000290": {
    normal: require("../../assets/audio/w-000290-normal.mp3"),
    slow: require("../../assets/audio/w-000290-slow.mp3"),
  },
  "w-000291": {
    normal: require("../../assets/audio/w-000291-normal.mp3"),
    slow: require("../../assets/audio/w-000291-slow.mp3"),
  },
  "w-000292": {
    normal: require("../../assets/audio/w-000292-normal.mp3"),
    slow: require("../../assets/audio/w-000292-slow.mp3"),
  },
  "w-000293": {
    normal: require("../../assets/audio/w-000293-normal.mp3"),
    slow: require("../../assets/audio/w-000293-slow.mp3"),
  },
  "w-000294": {
    normal: require("../../assets/audio/w-000294-normal.mp3"),
    slow: require("../../assets/audio/w-000294-slow.mp3"),
  },
  "w-000295": {
    normal: require("../../assets/audio/w-000295-normal.mp3"),
    slow: require("../../assets/audio/w-000295-slow.mp3"),
  },
  "w-000296": {
    normal: require("../../assets/audio/w-000296-normal.mp3"),
    slow: require("../../assets/audio/w-000296-slow.mp3"),
  },
  "w-000297": {
    normal: require("../../assets/audio/w-000297-normal.mp3"),
    slow: require("../../assets/audio/w-000297-slow.mp3"),
  },
  "w-000298": {
    normal: require("../../assets/audio/w-000298-normal.mp3"),
    slow: require("../../assets/audio/w-000298-slow.mp3"),
  },
  "w-000299": {
    normal: require("../../assets/audio/w-000299-normal.mp3"),
    slow: require("../../assets/audio/w-000299-slow.mp3"),
  },
  "w-000300": {
    normal: require("../../assets/audio/w-000300-normal.mp3"),
    slow: require("../../assets/audio/w-000300-slow.mp3"),
  },
  "w-000301": {
    normal: require("../../assets/audio/w-000301-normal.mp3"),
    slow: require("../../assets/audio/w-000301-slow.mp3"),
  },
  "w-000302": {
    normal: require("../../assets/audio/w-000302-normal.mp3"),
    slow: require("../../assets/audio/w-000302-slow.mp3"),
  },
  "w-000303": {
    normal: require("../../assets/audio/w-000303-normal.mp3"),
    slow: require("../../assets/audio/w-000303-slow.mp3"),
  },
  "w-000304": {
    normal: require("../../assets/audio/w-000304-normal.mp3"),
    slow: require("../../assets/audio/w-000304-slow.mp3"),
  },
  "w-000305": {
    normal: require("../../assets/audio/w-000305-normal.mp3"),
    slow: require("../../assets/audio/w-000305-slow.mp3"),
  },
  "w-000306": {
    normal: require("../../assets/audio/w-000306-normal.mp3"),
    slow: require("../../assets/audio/w-000306-slow.mp3"),
  },
  "w-000307": {
    normal: require("../../assets/audio/w-000307-normal.mp3"),
    slow: require("../../assets/audio/w-000307-slow.mp3"),
  },
  "w-000308": {
    normal: require("../../assets/audio/w-000308-normal.mp3"),
    slow: require("../../assets/audio/w-000308-slow.mp3"),
  },
  "w-000309": {
    normal: require("../../assets/audio/w-000309-normal.mp3"),
    slow: require("../../assets/audio/w-000309-slow.mp3"),
  },
  "w-000310": {
    normal: require("../../assets/audio/w-000310-normal.mp3"),
    slow: require("../../assets/audio/w-000310-slow.mp3"),
  },
  "w-000311": {
    normal: require("../../assets/audio/w-000311-normal.mp3"),
    slow: require("../../assets/audio/w-000311-slow.mp3"),
  },
  "w-000312": {
    normal: require("../../assets/audio/w-000312-normal.mp3"),
    slow: require("../../assets/audio/w-000312-slow.mp3"),
  },
  "w-000313": {
    normal: require("../../assets/audio/w-000313-normal.mp3"),
    slow: require("../../assets/audio/w-000313-slow.mp3"),
  },
  "w-000314": {
    normal: require("../../assets/audio/w-000314-normal.mp3"),
    slow: require("../../assets/audio/w-000314-slow.mp3"),
  },
  "w-000315": {
    normal: require("../../assets/audio/w-000315-normal.mp3"),
    slow: require("../../assets/audio/w-000315-slow.mp3"),
  },
  "w-000316": {
    normal: require("../../assets/audio/w-000316-normal.mp3"),
    slow: require("../../assets/audio/w-000316-slow.mp3"),
  },
  "w-000317": {
    normal: require("../../assets/audio/w-000317-normal.mp3"),
    slow: require("../../assets/audio/w-000317-slow.mp3"),
  },
  "w-000318": {
    normal: require("../../assets/audio/w-000318-normal.mp3"),
    slow: require("../../assets/audio/w-000318-slow.mp3"),
  },
  "w-000319": {
    normal: require("../../assets/audio/w-000319-normal.mp3"),
    slow: require("../../assets/audio/w-000319-slow.mp3"),
  },
  "w-000320": {
    normal: require("../../assets/audio/w-000320-normal.mp3"),
    slow: require("../../assets/audio/w-000320-slow.mp3"),
  },
  "w-000321": {
    normal: require("../../assets/audio/w-000321-normal.mp3"),
    slow: require("../../assets/audio/w-000321-slow.mp3"),
  },
  "w-000322": {
    normal: require("../../assets/audio/w-000322-normal.mp3"),
    slow: require("../../assets/audio/w-000322-slow.mp3"),
  },
  "w-000323": {
    normal: require("../../assets/audio/w-000323-normal.mp3"),
    slow: require("../../assets/audio/w-000323-slow.mp3"),
  },
  "w-000324": {
    normal: require("../../assets/audio/w-000324-normal.mp3"),
    slow: require("../../assets/audio/w-000324-slow.mp3"),
  },
  "w-000325": {
    normal: require("../../assets/audio/w-000325-normal.mp3"),
    slow: require("../../assets/audio/w-000325-slow.mp3"),
  },
  "w-000326": {
    normal: require("../../assets/audio/w-000326-normal.mp3"),
    slow: require("../../assets/audio/w-000326-slow.mp3"),
  },
  "w-000327": {
    normal: require("../../assets/audio/w-000327-normal.mp3"),
    slow: require("../../assets/audio/w-000327-slow.mp3"),
  },
  "w-000328": {
    normal: require("../../assets/audio/w-000328-normal.mp3"),
    slow: require("../../assets/audio/w-000328-slow.mp3"),
  },
  "w-000329": {
    normal: require("../../assets/audio/w-000329-normal.mp3"),
    slow: require("../../assets/audio/w-000329-slow.mp3"),
  },
  "w-000330": {
    normal: require("../../assets/audio/w-000330-normal.mp3"),
    slow: require("../../assets/audio/w-000330-slow.mp3"),
  },
  "w-000331": {
    normal: require("../../assets/audio/w-000331-normal.mp3"),
    slow: require("../../assets/audio/w-000331-slow.mp3"),
  },
  "w-000332": {
    normal: require("../../assets/audio/w-000332-normal.mp3"),
    slow: require("../../assets/audio/w-000332-slow.mp3"),
  },
  "w-000333": {
    normal: require("../../assets/audio/w-000333-normal.mp3"),
    slow: require("../../assets/audio/w-000333-slow.mp3"),
  },
  "w-000334": {
    normal: require("../../assets/audio/w-000334-normal.mp3"),
    slow: require("../../assets/audio/w-000334-slow.mp3"),
  },
  "w-000335": {
    normal: require("../../assets/audio/w-000335-normal.mp3"),
    slow: require("../../assets/audio/w-000335-slow.mp3"),
  },
  "w-000336": {
    normal: require("../../assets/audio/w-000336-normal.mp3"),
    slow: require("../../assets/audio/w-000336-slow.mp3"),
  },
  "w-000337": {
    normal: require("../../assets/audio/w-000337-normal.mp3"),
    slow: require("../../assets/audio/w-000337-slow.mp3"),
  },
  "w-000338": {
    normal: require("../../assets/audio/w-000338-normal.mp3"),
    slow: require("../../assets/audio/w-000338-slow.mp3"),
  },
  "w-000339": {
    normal: require("../../assets/audio/w-000339-normal.mp3"),
    slow: require("../../assets/audio/w-000339-slow.mp3"),
  },
  "w-000340": {
    normal: require("../../assets/audio/w-000340-normal.mp3"),
    slow: require("../../assets/audio/w-000340-slow.mp3"),
  },
  "w-000341": {
    normal: require("../../assets/audio/w-000341-normal.mp3"),
    slow: require("../../assets/audio/w-000341-slow.mp3"),
  },
  "w-000342": {
    normal: require("../../assets/audio/w-000342-normal.mp3"),
    slow: require("../../assets/audio/w-000342-slow.mp3"),
  },
  "w-000343": {
    normal: require("../../assets/audio/w-000343-normal.mp3"),
    slow: require("../../assets/audio/w-000343-slow.mp3"),
  },
  "w-000344": {
    normal: require("../../assets/audio/w-000344-normal.mp3"),
    slow: require("../../assets/audio/w-000344-slow.mp3"),
  },
  "w-000345": {
    normal: require("../../assets/audio/w-000345-normal.mp3"),
    slow: require("../../assets/audio/w-000345-slow.mp3"),
  },
  "w-000346": {
    normal: require("../../assets/audio/w-000346-normal.mp3"),
    slow: require("../../assets/audio/w-000346-slow.mp3"),
  },
  "w-000347": {
    normal: require("../../assets/audio/w-000347-normal.mp3"),
    slow: require("../../assets/audio/w-000347-slow.mp3"),
  },
  "w-000348": {
    normal: require("../../assets/audio/w-000348-normal.mp3"),
    slow: require("../../assets/audio/w-000348-slow.mp3"),
  },
  "w-000349": {
    normal: require("../../assets/audio/w-000349-normal.mp3"),
    slow: require("../../assets/audio/w-000349-slow.mp3"),
  },
  "w-000350": {
    normal: require("../../assets/audio/w-000350-normal.mp3"),
    slow: require("../../assets/audio/w-000350-slow.mp3"),
  },
  "w-000351": {
    normal: require("../../assets/audio/w-000351-normal.mp3"),
    slow: require("../../assets/audio/w-000351-slow.mp3"),
  },
  "w-000352": {
    normal: require("../../assets/audio/w-000352-normal.mp3"),
    slow: require("../../assets/audio/w-000352-slow.mp3"),
  },
  "w-000353": {
    normal: require("../../assets/audio/w-000353-normal.mp3"),
    slow: require("../../assets/audio/w-000353-slow.mp3"),
  },
  "w-000354": {
    normal: require("../../assets/audio/w-000354-normal.mp3"),
    slow: require("../../assets/audio/w-000354-slow.mp3"),
  },
  "w-000355": {
    normal: require("../../assets/audio/w-000355-normal.mp3"),
    slow: require("../../assets/audio/w-000355-slow.mp3"),
  },
  "w-000356": {
    normal: require("../../assets/audio/w-000356-normal.mp3"),
    slow: require("../../assets/audio/w-000356-slow.mp3"),
  },
  "w-000357": {
    normal: require("../../assets/audio/w-000357-normal.mp3"),
    slow: require("../../assets/audio/w-000357-slow.mp3"),
  },
  "w-000358": {
    normal: require("../../assets/audio/w-000358-normal.mp3"),
    slow: require("../../assets/audio/w-000358-slow.mp3"),
  },
  "w-000359": {
    normal: require("../../assets/audio/w-000359-normal.mp3"),
    slow: require("../../assets/audio/w-000359-slow.mp3"),
  },
  "w-000360": {
    normal: require("../../assets/audio/w-000360-normal.mp3"),
    slow: require("../../assets/audio/w-000360-slow.mp3"),
  },
  "w-000361": {
    normal: require("../../assets/audio/w-000361-normal.mp3"),
    slow: require("../../assets/audio/w-000361-slow.mp3"),
  },
  "w-000362": {
    normal: require("../../assets/audio/w-000362-normal.mp3"),
    slow: require("../../assets/audio/w-000362-slow.mp3"),
  },
  "w-000363": {
    normal: require("../../assets/audio/w-000363-normal.mp3"),
    slow: require("../../assets/audio/w-000363-slow.mp3"),
  },
  "w-000364": {
    normal: require("../../assets/audio/w-000364-normal.mp3"),
    slow: require("../../assets/audio/w-000364-slow.mp3"),
  },
  "w-000365": {
    normal: require("../../assets/audio/w-000365-normal.mp3"),
    slow: require("../../assets/audio/w-000365-slow.mp3"),
  },
  "w-000366": {
    normal: require("../../assets/audio/w-000366-normal.mp3"),
    slow: require("../../assets/audio/w-000366-slow.mp3"),
  },
  "w-000367": {
    normal: require("../../assets/audio/w-000367-normal.mp3"),
    slow: require("../../assets/audio/w-000367-slow.mp3"),
  },
  "w-000368": {
    normal: require("../../assets/audio/w-000368-normal.mp3"),
    slow: require("../../assets/audio/w-000368-slow.mp3"),
  },
  "w-000369": {
    normal: require("../../assets/audio/w-000369-normal.mp3"),
    slow: require("../../assets/audio/w-000369-slow.mp3"),
  },
  "w-000370": {
    normal: require("../../assets/audio/w-000370-normal.mp3"),
    slow: require("../../assets/audio/w-000370-slow.mp3"),
  },
  "w-000371": {
    normal: require("../../assets/audio/w-000371-normal.mp3"),
    slow: require("../../assets/audio/w-000371-slow.mp3"),
  },
  "w-000372": {
    normal: require("../../assets/audio/w-000372-normal.mp3"),
    slow: require("../../assets/audio/w-000372-slow.mp3"),
  },
  "w-000373": {
    normal: require("../../assets/audio/w-000373-normal.mp3"),
    slow: require("../../assets/audio/w-000373-slow.mp3"),
  },
  "w-000374": {
    normal: require("../../assets/audio/w-000374-normal.mp3"),
    slow: require("../../assets/audio/w-000374-slow.mp3"),
  },
  "w-000375": {
    normal: require("../../assets/audio/w-000375-normal.mp3"),
    slow: require("../../assets/audio/w-000375-slow.mp3"),
  },
  "w-000376": {
    normal: require("../../assets/audio/w-000376-normal.mp3"),
    slow: require("../../assets/audio/w-000376-slow.mp3"),
  },
  "w-000377": {
    normal: require("../../assets/audio/w-000377-normal.mp3"),
    slow: require("../../assets/audio/w-000377-slow.mp3"),
  },
  "w-000378": {
    normal: require("../../assets/audio/w-000378-normal.mp3"),
    slow: require("../../assets/audio/w-000378-slow.mp3"),
  },
  "w-000379": {
    normal: require("../../assets/audio/w-000379-normal.mp3"),
    slow: require("../../assets/audio/w-000379-slow.mp3"),
  },
  "w-000380": {
    normal: require("../../assets/audio/w-000380-normal.mp3"),
    slow: require("../../assets/audio/w-000380-slow.mp3"),
  },
  "w-000381": {
    normal: require("../../assets/audio/w-000381-normal.mp3"),
    slow: require("../../assets/audio/w-000381-slow.mp3"),
  },
  "w-000382": {
    normal: require("../../assets/audio/w-000382-normal.mp3"),
    slow: require("../../assets/audio/w-000382-slow.mp3"),
  },
  "w-000383": {
    normal: require("../../assets/audio/w-000383-normal.mp3"),
    slow: require("../../assets/audio/w-000383-slow.mp3"),
  },
  "w-000384": {
    normal: require("../../assets/audio/w-000384-normal.mp3"),
    slow: require("../../assets/audio/w-000384-slow.mp3"),
  },
  "w-000385": {
    normal: require("../../assets/audio/w-000385-normal.mp3"),
    slow: require("../../assets/audio/w-000385-slow.mp3"),
  },
  "w-000386": {
    normal: require("../../assets/audio/w-000386-normal.mp3"),
    slow: require("../../assets/audio/w-000386-slow.mp3"),
  },
  "w-000387": {
    normal: require("../../assets/audio/w-000387-normal.mp3"),
    slow: require("../../assets/audio/w-000387-slow.mp3"),
  },
  "w-000388": {
    normal: require("../../assets/audio/w-000388-normal.mp3"),
    slow: require("../../assets/audio/w-000388-slow.mp3"),
  },
  "w-000389": {
    normal: require("../../assets/audio/w-000389-normal.mp3"),
    slow: require("../../assets/audio/w-000389-slow.mp3"),
  },
  "w-000390": {
    normal: require("../../assets/audio/w-000390-normal.mp3"),
    slow: require("../../assets/audio/w-000390-slow.mp3"),
  },
  "w-000391": {
    normal: require("../../assets/audio/w-000391-normal.mp3"),
    slow: require("../../assets/audio/w-000391-slow.mp3"),
  },
  "w-000392": {
    normal: require("../../assets/audio/w-000392-normal.mp3"),
    slow: require("../../assets/audio/w-000392-slow.mp3"),
  },
  "w-000393": {
    normal: require("../../assets/audio/w-000393-normal.mp3"),
    slow: require("../../assets/audio/w-000393-slow.mp3"),
  },
  "w-000394": {
    normal: require("../../assets/audio/w-000394-normal.mp3"),
    slow: require("../../assets/audio/w-000394-slow.mp3"),
  },
  "w-000395": {
    normal: require("../../assets/audio/w-000395-normal.mp3"),
    slow: require("../../assets/audio/w-000395-slow.mp3"),
  },
  "w-000396": {
    normal: require("../../assets/audio/w-000396-normal.mp3"),
    slow: require("../../assets/audio/w-000396-slow.mp3"),
  },
  "w-000397": {
    normal: require("../../assets/audio/w-000397-normal.mp3"),
    slow: require("../../assets/audio/w-000397-slow.mp3"),
  },
  "w-000398": {
    normal: require("../../assets/audio/w-000398-normal.mp3"),
    slow: require("../../assets/audio/w-000398-slow.mp3"),
  },
  "w-000399": {
    normal: require("../../assets/audio/w-000399-normal.mp3"),
    slow: require("../../assets/audio/w-000399-slow.mp3"),
  },
  "w-000400": {
    normal: require("../../assets/audio/w-000400-normal.mp3"),
    slow: require("../../assets/audio/w-000400-slow.mp3"),
  },
  "w-000401": {
    normal: require("../../assets/audio/w-000401-normal.mp3"),
    slow: require("../../assets/audio/w-000401-slow.mp3"),
  },
  "w-000402": {
    normal: require("../../assets/audio/w-000402-normal.mp3"),
    slow: require("../../assets/audio/w-000402-slow.mp3"),
  },
  "w-000403": {
    normal: require("../../assets/audio/w-000403-normal.mp3"),
    slow: require("../../assets/audio/w-000403-slow.mp3"),
  },
  "w-000404": {
    normal: require("../../assets/audio/w-000404-normal.mp3"),
    slow: require("../../assets/audio/w-000404-slow.mp3"),
  },
  "w-000405": {
    normal: require("../../assets/audio/w-000405-normal.mp3"),
    slow: require("../../assets/audio/w-000405-slow.mp3"),
  },
  "w-000406": {
    normal: require("../../assets/audio/w-000406-normal.mp3"),
    slow: require("../../assets/audio/w-000406-slow.mp3"),
  },
  "w-000407": {
    normal: require("../../assets/audio/w-000407-normal.mp3"),
    slow: require("../../assets/audio/w-000407-slow.mp3"),
  },
  "w-000408": {
    normal: require("../../assets/audio/w-000408-normal.mp3"),
    slow: require("../../assets/audio/w-000408-slow.mp3"),
  },
  "w-000409": {
    normal: require("../../assets/audio/w-000409-normal.mp3"),
    slow: require("../../assets/audio/w-000409-slow.mp3"),
  },
  "w-000410": {
    normal: require("../../assets/audio/w-000410-normal.mp3"),
    slow: require("../../assets/audio/w-000410-slow.mp3"),
  },
  "w-000411": {
    normal: require("../../assets/audio/w-000411-normal.mp3"),
    slow: require("../../assets/audio/w-000411-slow.mp3"),
  },
  "w-000412": {
    normal: require("../../assets/audio/w-000412-normal.mp3"),
    slow: require("../../assets/audio/w-000412-slow.mp3"),
  },
  "w-000413": {
    normal: require("../../assets/audio/w-000413-normal.mp3"),
    slow: require("../../assets/audio/w-000413-slow.mp3"),
  },
  "w-000414": {
    normal: require("../../assets/audio/w-000414-normal.mp3"),
    slow: require("../../assets/audio/w-000414-slow.mp3"),
  },
  "w-000415": {
    normal: require("../../assets/audio/w-000415-normal.mp3"),
    slow: require("../../assets/audio/w-000415-slow.mp3"),
  },
  "w-000416": {
    normal: require("../../assets/audio/w-000416-normal.mp3"),
    slow: require("../../assets/audio/w-000416-slow.mp3"),
  },
  "w-000417": {
    normal: require("../../assets/audio/w-000417-normal.mp3"),
    slow: require("../../assets/audio/w-000417-slow.mp3"),
  },
  "w-000418": {
    normal: require("../../assets/audio/w-000418-normal.mp3"),
    slow: require("../../assets/audio/w-000418-slow.mp3"),
  },
  "w-000419": {
    normal: require("../../assets/audio/w-000419-normal.mp3"),
    slow: require("../../assets/audio/w-000419-slow.mp3"),
  },
  "w-000420": {
    normal: require("../../assets/audio/w-000420-normal.mp3"),
    slow: require("../../assets/audio/w-000420-slow.mp3"),
  },
  "w-000421": {
    normal: require("../../assets/audio/w-000421-normal.mp3"),
    slow: require("../../assets/audio/w-000421-slow.mp3"),
  },
  "w-000422": {
    normal: require("../../assets/audio/w-000422-normal.mp3"),
    slow: require("../../assets/audio/w-000422-slow.mp3"),
  },
  "w-000423": {
    normal: require("../../assets/audio/w-000423-normal.mp3"),
    slow: require("../../assets/audio/w-000423-slow.mp3"),
  },
  "w-000424": {
    normal: require("../../assets/audio/w-000424-normal.mp3"),
    slow: require("../../assets/audio/w-000424-slow.mp3"),
  },
  "w-000425": {
    normal: require("../../assets/audio/w-000425-normal.mp3"),
    slow: require("../../assets/audio/w-000425-slow.mp3"),
  },
  "w-000426": {
    normal: require("../../assets/audio/w-000426-normal.mp3"),
    slow: require("../../assets/audio/w-000426-slow.mp3"),
  },
  "w-000427": {
    normal: require("../../assets/audio/w-000427-normal.mp3"),
    slow: require("../../assets/audio/w-000427-slow.mp3"),
  },
  "w-000428": {
    normal: require("../../assets/audio/w-000428-normal.mp3"),
    slow: require("../../assets/audio/w-000428-slow.mp3"),
  },
  "w-000429": {
    normal: require("../../assets/audio/w-000429-normal.mp3"),
    slow: require("../../assets/audio/w-000429-slow.mp3"),
  },
  "w-000430": {
    normal: require("../../assets/audio/w-000430-normal.mp3"),
    slow: require("../../assets/audio/w-000430-slow.mp3"),
  },
  "w-000431": {
    normal: require("../../assets/audio/w-000431-normal.mp3"),
    slow: require("../../assets/audio/w-000431-slow.mp3"),
  },
  "w-000432": {
    normal: require("../../assets/audio/w-000432-normal.mp3"),
    slow: require("../../assets/audio/w-000432-slow.mp3"),
  },
  "w-000433": {
    normal: require("../../assets/audio/w-000433-normal.mp3"),
    slow: require("../../assets/audio/w-000433-slow.mp3"),
  },
  "w-000434": {
    normal: require("../../assets/audio/w-000434-normal.mp3"),
    slow: require("../../assets/audio/w-000434-slow.mp3"),
  },
  "w-000435": {
    normal: require("../../assets/audio/w-000435-normal.mp3"),
    slow: require("../../assets/audio/w-000435-slow.mp3"),
  },
  "w-000436": {
    normal: require("../../assets/audio/w-000436-normal.mp3"),
    slow: require("../../assets/audio/w-000436-slow.mp3"),
  },
  "w-000437": {
    normal: require("../../assets/audio/w-000437-normal.mp3"),
    slow: require("../../assets/audio/w-000437-slow.mp3"),
  },
  "w-000438": {
    normal: require("../../assets/audio/w-000438-normal.mp3"),
    slow: require("../../assets/audio/w-000438-slow.mp3"),
  },
  "w-000439": {
    normal: require("../../assets/audio/w-000439-normal.mp3"),
    slow: require("../../assets/audio/w-000439-slow.mp3"),
  },
  "w-000440": {
    normal: require("../../assets/audio/w-000440-normal.mp3"),
    slow: require("../../assets/audio/w-000440-slow.mp3"),
  },
  "w-000441": {
    normal: require("../../assets/audio/w-000441-normal.mp3"),
    slow: require("../../assets/audio/w-000441-slow.mp3"),
  },
  "w-000442": {
    normal: require("../../assets/audio/w-000442-normal.mp3"),
    slow: require("../../assets/audio/w-000442-slow.mp3"),
  },
  "w-000443": {
    normal: require("../../assets/audio/w-000443-normal.mp3"),
    slow: require("../../assets/audio/w-000443-slow.mp3"),
  },
  "w-000444": {
    normal: require("../../assets/audio/w-000444-normal.mp3"),
    slow: require("../../assets/audio/w-000444-slow.mp3"),
  },
  "w-000445": {
    normal: require("../../assets/audio/w-000445-normal.mp3"),
    slow: require("../../assets/audio/w-000445-slow.mp3"),
  },
  "w-000446": {
    normal: require("../../assets/audio/w-000446-normal.mp3"),
    slow: require("../../assets/audio/w-000446-slow.mp3"),
  },
  "w-000447": {
    normal: require("../../assets/audio/w-000447-normal.mp3"),
    slow: require("../../assets/audio/w-000447-slow.mp3"),
  },
  "w-000448": {
    normal: require("../../assets/audio/w-000448-normal.mp3"),
    slow: require("../../assets/audio/w-000448-slow.mp3"),
  },
  "w-000449": {
    normal: require("../../assets/audio/w-000449-normal.mp3"),
    slow: require("../../assets/audio/w-000449-slow.mp3"),
  },
  "w-000450": {
    normal: require("../../assets/audio/w-000450-normal.mp3"),
    slow: require("../../assets/audio/w-000450-slow.mp3"),
  },
  "w-000451": {
    normal: require("../../assets/audio/w-000451-normal.mp3"),
    slow: require("../../assets/audio/w-000451-slow.mp3"),
  },
  "w-000452": {
    normal: require("../../assets/audio/w-000452-normal.mp3"),
    slow: require("../../assets/audio/w-000452-slow.mp3"),
  },
  "w-000453": {
    normal: require("../../assets/audio/w-000453-normal.mp3"),
    slow: require("../../assets/audio/w-000453-slow.mp3"),
  },
  "w-000454": {
    normal: require("../../assets/audio/w-000454-normal.mp3"),
    slow: require("../../assets/audio/w-000454-slow.mp3"),
  },
  "w-000455": {
    normal: require("../../assets/audio/w-000455-normal.mp3"),
    slow: require("../../assets/audio/w-000455-slow.mp3"),
  },
  "w-000456": {
    normal: require("../../assets/audio/w-000456-normal.mp3"),
    slow: require("../../assets/audio/w-000456-slow.mp3"),
  },
  "w-000457": {
    normal: require("../../assets/audio/w-000457-normal.mp3"),
    slow: require("../../assets/audio/w-000457-slow.mp3"),
  },
  "w-000458": {
    normal: require("../../assets/audio/w-000458-normal.mp3"),
    slow: require("../../assets/audio/w-000458-slow.mp3"),
  },
  "w-000459": {
    normal: require("../../assets/audio/w-000459-normal.mp3"),
    slow: require("../../assets/audio/w-000459-slow.mp3"),
  },
  "w-000460": {
    normal: require("../../assets/audio/w-000460-normal.mp3"),
    slow: require("../../assets/audio/w-000460-slow.mp3"),
  },
  "w-000461": {
    normal: require("../../assets/audio/w-000461-normal.mp3"),
    slow: require("../../assets/audio/w-000461-slow.mp3"),
  },
  "w-000462": {
    normal: require("../../assets/audio/w-000462-normal.mp3"),
    slow: require("../../assets/audio/w-000462-slow.mp3"),
  },
  "w-000463": {
    normal: require("../../assets/audio/w-000463-normal.mp3"),
    slow: require("../../assets/audio/w-000463-slow.mp3"),
  },
  "w-000464": {
    normal: require("../../assets/audio/w-000464-normal.mp3"),
    slow: require("../../assets/audio/w-000464-slow.mp3"),
  },
  "w-000465": {
    normal: require("../../assets/audio/w-000465-normal.mp3"),
    slow: require("../../assets/audio/w-000465-slow.mp3"),
  },
  "w-000466": {
    normal: require("../../assets/audio/w-000466-normal.mp3"),
    slow: require("../../assets/audio/w-000466-slow.mp3"),
  },
  "w-000467": {
    normal: require("../../assets/audio/w-000467-normal.mp3"),
    slow: require("../../assets/audio/w-000467-slow.mp3"),
  },
  "w-000468": {
    normal: require("../../assets/audio/w-000468-normal.mp3"),
    slow: require("../../assets/audio/w-000468-slow.mp3"),
  },
  "w-000469": {
    normal: require("../../assets/audio/w-000469-normal.mp3"),
    slow: require("../../assets/audio/w-000469-slow.mp3"),
  },
  "w-000470": {
    normal: require("../../assets/audio/w-000470-normal.mp3"),
    slow: require("../../assets/audio/w-000470-slow.mp3"),
  },
  "w-000471": {
    normal: require("../../assets/audio/w-000471-normal.mp3"),
    slow: require("../../assets/audio/w-000471-slow.mp3"),
  },
  "w-000472": {
    normal: require("../../assets/audio/w-000472-normal.mp3"),
    slow: require("../../assets/audio/w-000472-slow.mp3"),
  },
  "w-000473": {
    normal: require("../../assets/audio/w-000473-normal.mp3"),
    slow: require("../../assets/audio/w-000473-slow.mp3"),
  },
  "w-000474": {
    normal: require("../../assets/audio/w-000474-normal.mp3"),
    slow: require("../../assets/audio/w-000474-slow.mp3"),
  },
  "w-000475": {
    normal: require("../../assets/audio/w-000475-normal.mp3"),
    slow: require("../../assets/audio/w-000475-slow.mp3"),
  },
  "w-000476": {
    normal: require("../../assets/audio/w-000476-normal.mp3"),
    slow: require("../../assets/audio/w-000476-slow.mp3"),
  },
  "w-000477": {
    normal: require("../../assets/audio/w-000477-normal.mp3"),
    slow: require("../../assets/audio/w-000477-slow.mp3"),
  },
  "w-000478": {
    normal: require("../../assets/audio/w-000478-normal.mp3"),
    slow: require("../../assets/audio/w-000478-slow.mp3"),
  },
  "w-000479": {
    normal: require("../../assets/audio/w-000479-normal.mp3"),
    slow: require("../../assets/audio/w-000479-slow.mp3"),
  },
  "w-000480": {
    normal: require("../../assets/audio/w-000480-normal.mp3"),
    slow: require("../../assets/audio/w-000480-slow.mp3"),
  },
  "w-000481": {
    normal: require("../../assets/audio/w-000481-normal.mp3"),
    slow: require("../../assets/audio/w-000481-slow.mp3"),
  },
  "w-000482": {
    normal: require("../../assets/audio/w-000482-normal.mp3"),
    slow: require("../../assets/audio/w-000482-slow.mp3"),
  },
  "w-000483": {
    normal: require("../../assets/audio/w-000483-normal.mp3"),
    slow: require("../../assets/audio/w-000483-slow.mp3"),
  },
  "w-000484": {
    normal: require("../../assets/audio/w-000484-normal.mp3"),
    slow: require("../../assets/audio/w-000484-slow.mp3"),
  },
  "w-000485": {
    normal: require("../../assets/audio/w-000485-normal.mp3"),
    slow: require("../../assets/audio/w-000485-slow.mp3"),
  },
  "w-000486": {
    normal: require("../../assets/audio/w-000486-normal.mp3"),
    slow: require("../../assets/audio/w-000486-slow.mp3"),
  },
  "w-000487": {
    normal: require("../../assets/audio/w-000487-normal.mp3"),
    slow: require("../../assets/audio/w-000487-slow.mp3"),
  },
  "w-000488": {
    normal: require("../../assets/audio/w-000488-normal.mp3"),
    slow: require("../../assets/audio/w-000488-slow.mp3"),
  },
  "w-000489": {
    normal: require("../../assets/audio/w-000489-normal.mp3"),
    slow: require("../../assets/audio/w-000489-slow.mp3"),
  },
  "w-000490": {
    normal: require("../../assets/audio/w-000490-normal.mp3"),
    slow: require("../../assets/audio/w-000490-slow.mp3"),
  },
  "w-000491": {
    normal: require("../../assets/audio/w-000491-normal.mp3"),
    slow: require("../../assets/audio/w-000491-slow.mp3"),
  },
  "w-000492": {
    normal: require("../../assets/audio/w-000492-normal.mp3"),
    slow: require("../../assets/audio/w-000492-slow.mp3"),
  },
  "w-000493": {
    normal: require("../../assets/audio/w-000493-normal.mp3"),
    slow: require("../../assets/audio/w-000493-slow.mp3"),
  },
  "w-000494": {
    normal: require("../../assets/audio/w-000494-normal.mp3"),
    slow: require("../../assets/audio/w-000494-slow.mp3"),
  },
  "w-000495": {
    normal: require("../../assets/audio/w-000495-normal.mp3"),
    slow: require("../../assets/audio/w-000495-slow.mp3"),
  },
  "w-000496": {
    normal: require("../../assets/audio/w-000496-normal.mp3"),
    slow: require("../../assets/audio/w-000496-slow.mp3"),
  },
  "w-000497": {
    normal: require("../../assets/audio/w-000497-normal.mp3"),
    slow: require("../../assets/audio/w-000497-slow.mp3"),
  },
  "w-000498": {
    normal: require("../../assets/audio/w-000498-normal.mp3"),
    slow: require("../../assets/audio/w-000498-slow.mp3"),
  },
  "w-000499": {
    normal: require("../../assets/audio/w-000499-normal.mp3"),
    slow: require("../../assets/audio/w-000499-slow.mp3"),
  },
  "w-000500": {
    normal: require("../../assets/audio/w-000500-normal.mp3"),
    slow: require("../../assets/audio/w-000500-slow.mp3"),
  },
};
